version: '3.8'

services:
  backend:
    image: sensesis/adcanvas-back:1.0.11  # 최신 이미지 태그 사용
    container_name: Adcanvas-Backend
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - Adcanvas-Net
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"


networks:
  Adcanvas-Net:
    external: true
